interface Character {
  name: string;
  englishNameInJP: string;
  englishNameInEN: string;
  year: string; // "year1" format or original
  releaseDate: string; //ISO 8601 format
}
// 並び順は公式サイトのキャラクター一覧に合わせている(日本語版・英語版で同じ順)。
// 追加キャラは後ろに並ぶので、無印18人の後は4人ずつyear1・year2…と区切れる。
// 無印18人のreleaseDateは本体の発売日。
export const characterList: Character[] = [
  {
    name: "ルーク",
    englishNameInJP: "LUKE",
    englishNameInEN: "LUKE",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ジェイミー",
    englishNameInJP: "JAMIE",
    englishNameInEN: "JAMIE",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "マノン",
    englishNameInJP: "MANON",
    englishNameInEN: "MANON",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "キンバリー",
    englishNameInJP: "KIMBERLY",
    englishNameInEN: "KIMBERLY",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "マリーザ",
    englishNameInJP: "MARISA",
    englishNameInEN: "MARISA",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "リリー",
    englishNameInJP: "LILY",
    englishNameInEN: "LILY",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "JP",
    englishNameInJP: "JP",
    englishNameInEN: "JP",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ジュリ",
    englishNameInJP: "JURI",
    englishNameInEN: "JURI",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ディージェイ",
    englishNameInJP: "DEE JAY",
    englishNameInEN: "DEE JAY",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "キャミィ",
    englishNameInJP: "CAMMY",
    englishNameInEN: "CAMMY",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "リュウ",
    englishNameInJP: "RYU",
    englishNameInEN: "RYU",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "エドモンド本田",
    englishNameInJP: "E.HONDA",
    englishNameInEN: "E.HONDA",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ブランカ",
    englishNameInJP: "BLANKA",
    englishNameInEN: "BLANKA",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ガイル",
    englishNameInJP: "GUILE",
    englishNameInEN: "GUILE",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ケン",
    englishNameInJP: "KEN",
    englishNameInEN: "KEN",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "春麗",
    englishNameInJP: "CHUN-LI",
    englishNameInEN: "CHUN-LI",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ザンギエフ",
    englishNameInJP: "ZANGIEF",
    englishNameInEN: "ZANGIEF",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ダルシム",
    englishNameInJP: "DHALSIM",
    englishNameInEN: "DHALSIM",
    year: "original",
    releaseDate: "2023-06-02",
  },
  {
    name: "ラシード",
    englishNameInJP: "RASHID",
    englishNameInEN: "RASHID",
    year: "year1",
    releaseDate: "2023-07-24",
  },
  {
    name: "A.K.I.",
    englishNameInJP: "A.K.I.",
    englishNameInEN: "A.K.I.",
    year: "year1",
    releaseDate: "2023-09-27",
  },
  {
    name: "ED",
    englishNameInJP: "ED",
    englishNameInEN: "ED",
    year: "year1",
    releaseDate: "2024-02-27",
  },
  {
    name: "豪鬼",
    englishNameInJP: "GOUKI",
    englishNameInEN: "AKUMA",
    year: "year1",
    releaseDate: "2024-05-22",
  },
  {
    name: "ベガ",
    englishNameInJP: "VEGA",
    englishNameInEN: "M.BISON",
    year: "year2",
    releaseDate: "2024-06-26",
  },
  {
    name: "テリー",
    englishNameInJP: "TERRY",
    englishNameInEN: "TERRY",
    year: "year2",
    releaseDate: "2024-09-24",
  },
  {
    name: "舞",
    englishNameInJP: "MAI",
    englishNameInEN: "MAI",
    year: "year2",
    releaseDate: "2025-02-05",
  },
  {
    name: "エレナ",
    englishNameInJP: "ELENA",
    englishNameInEN: "ELENA",
    year: "year2",
    releaseDate: "2025-06-05",
  },
  {
    name: "サガット",
    englishNameInJP: "SAGAT",
    englishNameInEN: "SAGAT",
    year: "year3",
    releaseDate: "2025-08-05",
  },
  {
    name: "C.ヴァイパー",
    englishNameInJP: "C.VIPER",
    englishNameInEN: "C.VIPER",
    year: "year3",
    releaseDate: "2025-10-15",
  },
  {
    name: "アレックス",
    englishNameInJP: "ALEX",
    englishNameInEN: "ALEX",
    year: "year3",
    releaseDate: "2026-03-17",
  },
  {
    name: "イングリッド",
    englishNameInJP: "INGRID",
    englishNameInEN: "INGRID",
    year: "year3",
    releaseDate: "2026-05-28",
  },
  {
    name: "ヤスミン",
    englishNameInJP: "YASMINE",
    englishNameInEN: "YASMINE",
    year: "year4",
    releaseDate: "2026-08-03",
  },
];
